### ISSUE TITLE
Missing space in weather based schedule list item

### ISSUE THREAD

**Issue by lthill** [martinpihrt/OSPy#1]
https://github.com/martinpihrt/OSPy/blob/0ee8ffa5c5fc038355635aaf5f6d7982cc045f0e/ospy/programs.py#L272

The current line is missing a space character between the text 'Weather based schedule on' and the following string of days.

Line should be:
result = _('Weather based schedule on') + " " +  ' '.join([self._day_str(x) for x in set([int(y/1440) for y, z in self.type_data[-1]])])

**Comment by martinpihrt** [comment]
Fixed missing space in text 'Weather based schedule on' and the following string of days.
Thanks 
MP
