### ISSUE TITLE
Dark sky free plan is discontinued

### ISSUE THREAD

**Issue by yehuday** [martinpihrt/OSPy#10]
- [x] before sending the mistakes I read page: <https://pihrt.com/elektronika/248-moje-rapsberry-pi-zavlazovani-zahrady>
- [ ] is a hardware problem with www.pihrt.com printed board
- [ ] is a software OSPy <https://github.com/martinpihrt/OSPy> problem
- [x] is a plugin <https://github.com/martinpihrt/OSPy-plugins> problem

i have a free dark sky API key but it doesn't work anymore. 
any plans to move to something like https://www.weatherapi.com/ ?
looks like they have a pretty good plan

**Comment by martinpihrt** [comment]
Hi, looks interesting. I will try to switch to this service (I will look into it during the summer).
Martin

**Comment by martinpihrt** [comment]
Updated weather system to use Storm Glass instead of Dark Sky.
