### ISSUE TITLE
Reset password from code

### ISSUE THREAD

**Issue by yehuday** [martinpihrt/OSPy#15]
- [x] before sending the mistakes I read page: <https://pihrt.com/elektronika/248-moje-rapsberry-pi-zavlazovani-zahrady>
- [ ] is a hardware problem with www.pihrt.com printed board
- [x] is a software OSPy <https://github.com/martinpihrt/OSPy> problem
- [ ] is a plugin <https://github.com/martinpihrt/OSPy-plugins> problem

For some reason i an unable to login into OSPY even though i definitely use the correct password
I still have SSH access and can edit the code so i want to reset my user password instead of reseting the entire OSPY to defaults

Appreciate any tip

yehuda

**Comment by martinpihrt** [comment]
Currently there is no way to bypass the login and not switch ospy to default (by removing the ospy/data and ospy/backup folders).
If you can wait, in the next week I'll write a script run over SSH that deletes the password but leaves the rest.
Martin

**Comment by martinpihrt** [comment]
Hi,
The back_door.py file has been added to the OSPy folder, which allows logging into OSPy in case we cannot log in (or do not know the password). We will not lose the settings and log history in OSPy as if we used the default OSPy installation (after deleting the ospy/data and ospy/backup files). The default name and password to run the **sudo python3 back_door.py** file will be admin/admin.

**Comment by yehuday** [comment]
Thanks a lot martin !
i ran the script but unfortunately still couldn't login with admin:admin
I tried a different browser but still no luck
Look like something basic is broken. i might re-install after all
