### ISSUE TITLE
Incorrect sign in pem scheduler?

### ISSUE THREAD

**Issue by lthill** [martinpihrt/OSPy#2]
I was merging your code with the changes by Rimco and it appears at some point a minus sign was swapped with a plus on line 104 / 105.

pems = [x for x in pems if x[0] >= now - datetime.timedelta(hours=3)].

https://github.com/martinpihrt/OSPy/blob/e644261d7ab0473656dc0144cf253a3930b646a0/ospy/programs.py#L105

**Comment by martinpihrt** [comment]
Hi,
the code is fine - means something went away and + something added. The code only changed in this: time=1 to time=3. See here: https://github.com/Rimco/OSPy/commit/89c7efb34d1a88f27aca1edae0b97c17d9996d8c#diff-93fb43bd8cb2e1722ec9c8863a815f43R104

**Comment by lthill** [comment]
Ah. I traced it down. There is definitely a difference. Going back through blame I see it the change in signs showed up a commit by Rimco after your fork.

The statement in question is: 
```
pems = [x for x in pems if x[0] >= now + datetime.timedelta(hours=3)]
```
And the sign in question is: ... now (+/-) datetime ...

Your fork uses "+": https://github.com/martinpihrt/OSPy/blob/e644261d7ab0473656dc0144cf253a3930b646a0/ospy/programs.py#L105

While Rimco changed the sign in line 104 from "+" to "-" with commit [420dfc](https://github.com/Rimco/OSPy/commit/420dfc729e0143dac28e58009d4e46021b7cf64b?diff=unified) . The sign remains "-" up to the present [89c7efb](https://github.com/Rimco/OSPy/blob/2d1e628c12543cccd6d8ac5edbdb1efb6b07d35d/ospy/programs.py#L104). I found the difference when I tried to merge 89c7efb with your code.

It is interesting that the very same statement started out with a "-" as shown in line 102 of programs.py in commit [d25dec](https://github.com/Rimco/OSPy/blame/adf653a269e3c7dfe6729fcada3317478a8e6c1b/ospy/programs.py#L102)
```
pems = [x for x in pems if x[0] >= now - datetime.timedelta(hours=12)] 
```
I am not sure which one is correct. I am only pointing out the difference. Perhaps Rimco could elaborate.

**Comment by martinpihrt** [comment]
Hello lthill ,
This is my fault I apologize. I can no longer do the merger with Rimco in OSPy, but I have to do it manually and this is generating fault.

Regards 
Martin

**Comment by martinpihrt** [comment]
Thank's lthill -> Fixed
M
