### ISSUE TITLE
Station Grouping

### ISSUE THREAD

**Issue by garudaonekh** [martinpihrt/OSPy#4]
Hi,
1. Can we group station together for easy naming and scheduling?
2. Can we set a group of station to be run sequentially but not all sequentially? 
 
Here's my problem: we have several greenhouses, each greenhouse has around 8 to 10 stations and we need to irrigate the valve in the same greenhouse sequentially but we need to irrigate all the greenhouse at the same time.

Thanks;

**Comment by martinpihrt** [comment]
Hi,
yes, the stations you want to control are assigned to each program.
Programs can run together at the same time. The behavior can be set in the station settings (whether the stations are to be started one after the other within the program or next to each other).
Example:
16 stations connected
station settings 1-16 will be set as a sequence
program 1 will start at 10 o'clock. Stations 1-8 are assigned to this program
program 2 will also start at 10 o'clock. Stations 9-16 are assigned to this program.
At 10 o'clock these stations will be started one after the other 1 + 9 then 2 + 10, 3 + 11 ....

Stations can be named just as programs can be named.
The system can also use virtual stations with ESP32, which have relays and are connected via Wi-Fi. I'm sending a preview of my irrigation system (it's in Czech, but it will be enough to understand). The system is in Czech, English and Slovak)
Martin
![Screenshot 2021-08-04 at 12-39-50 Chata - Domů](https://user-images.githubusercontent.com/7847139/128167844-cebf9dfb-8ec3-4d2d-b3b8-1723a7b3fc3c.png)
![Screenshot 2021-08-04 at 12-39-40 Chata - Programy](https://user-images.githubusercontent.com/7847139/128167855-b0114449-bd56-4289-86ed-dfdefde56522.png)
![Screenshot 2021-08-04 at 12-39-30 Chata - Stanice](https://user-images.githubusercontent.com/7847139/128167864-ca1ef5dd-f4ab-4946-ac37-7aeb5e8897c0.png)

**Comment by garudaonekh** [comment]
Much appreciated! Thanks for your elaborated explanation. That solved my problem
