### ISSUE TITLE
Latching support

### ISSUE THREAD

**Issue by garudaonekh** [martinpihrt/OSPy#7]
Hello,
Does your controller or ESP32 expander support latching valve?

**Comment by martinpihrt** [comment]
Hi,
What do you mean by latching valve?

**Comment by garudaonekh** [comment]
I mean pulse valve, which require only 50-500millisecond of power to turn on or off the valve. It's perfect for battery powered valve.

**Comment by martinpihrt** [comment]
Using the OSPy, the shortest time for closing the multisensor relay to 1 second can be set (this would also work with valve).
example:
curl -s -O --connect-timeout 2 --data 're=1&run=1' 'http://192.168.88.237/0123456789abcdef'
where run=1 is time 1sec for relay ON
curl -s -O --connect-timeout 2 --data 're=0' 'http://192.168.88.237/0123456789abcdef' for OFF

**Comment by garudaonekh** [comment]
Latching valve will require positive voltage to turn on and reverse negative voltage to close the valve. 
So if we use relay as workaround, we'll need two relays and 2 diodes.

**Comment by martinpihrt** [comment]
in this case, a multisensor cannot be used to control these valves. This may be the subject of another version of the sensor with multiple relays and a choice of valve types. This is not possible at this time

**Comment by martinpihrt** [comment]
Hi, in new PCB version 1.1 is suported two relay for latch valves...
https://pihrt.com/elektronika/448-esp32-multisnimac-hw1-1-pro-opensprinkler-system
i will need to add support to the firmware to support 2 relays...

**Comment by martinpihrt** [comment]
Hi,
new HW1.1 now supported two outputs for latch valves...
https://pihrt.com/elektronika/448-esp32-multisnimac-hw1-1-pro-opensprinkler-syste
![20211014_110345](https://user-images.githubusercontent.com/7847139/137308687-7ac3cd30-d357-4804-bda0-f60853d0c2f7.jpg)
![20211014_104941](https://user-images.githubusercontent.com/7847139/137308692-5b4c71f6-03ff-4465-ba89-8e97d0328170.jpg)
![20211014_105001](https://user-images.githubusercontent.com/7847139/137308696-a6f4f906-b649-45df-bbb1-c7fc92e046e3.jpg)
m

**Comment by garudaonekh** [comment]
sorry, i was busy and not seen this. why your latching valve has three wire?

**Comment by martinpihrt** [comment]
Hi, here is how connect
https://pihrt.com/elektronika/451-pripojeni-ruznych-ventilu-k-multisnimaci-esp32-ospy
