### ISSUE TITLE
ESP32 Range to the RPI

### ISSUE THREAD

**Issue by garudaonekh** [martinpihrt/OSPy#8]
Hi,
What is the best range you can get between the ESP32 and the Raspberry PI? Or do you have any suggestion to improve the range.

I test on a farm, the range is terrible. I can't hardly get the ESP32 to work with the Raspberry above 30~40 meters. I need to use wifi repeater(which is causing another point of failure). I think it's because the Raspberry pi's wifi itself is weak.

**Comment by martinpihrt** [comment]
Hi,
I don't use Wi-Fi with the Raspberry Pi. I have a Raspberry Pi connected to my LAN network. At the house has an external wifi router from the company mikrotik (the company is not important, but the outdoor design is important).
It is important to use the correct external antenna on the ESP32 sensor!
Example of an antenna I use: 
antena https://www.i4wifi.cz/cs/211045-waverf-10-dbi-vsesm-vnitrni-antena-rsma-2-4-ghz
cable https://www.i4wifi.cz/cs/210404-waverf-pigtail-u-fl-rsma-pro-minipci
I have no problem with the connection (I have a sensor board 50 m away from the Wi-Fi).
Best regards
Martin

**Comment by garudaonekh** [comment]
to avoid wifi router, I use USB 4G dongle on RPI and make RPI as Access point so the ESP is connected to the RPI wifi. I use ESP32 wroom-32u.  maybe i should try a better quality wifi antenna. I try several Chinese made antenna but they seem the same
